# Generated by Django 4.0.6 on 2022-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('firstCommit', models.DateField()),
                ('lastCommit', models.DateField()),
                ('mainStack', models.CharField(choices=[('Python', 'Python'), ('Js', 'Javascript'), ('C#', 'C#'), ('Java', 'Java')], max_length=6)),
                ('description', models.CharField(max_length=500)),
                ('bannerImg', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
